app = "smc-scanner-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONIOENCODING = "utf-8"

# Cấu hình chạy Machine như một Cronjob (mỗi 15 phút tại phút 01, 16, 31, 46)
[machine]
  schedule = "1,16,31,46 * * * *"
